language: rust
sudo: false

# run builds for all the trains (and more)
rust:
- nightly

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
- |
    travis-cargo --only nightly build &&
    travis-cargo --only nightly test -- --features unstable-testing &&
    travis-cargo --only nightly bench &&
    travis-cargo --only stable doc 

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""
